import type { Metadata } from 'next'

import { inter } from '@next/styles/fonts'

import '@next/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IRootLayout {
  children: React.ReactNode
}

export default function RootLayout({ children, }: IRootLayout) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
